### PR TITLE
Added kms:Tag* permission to key to allow tagging

### PR DESCRIPTION
**Pull request by erikdj**
The permissions in version 0.4.0 do not grant kms:Tag* permissions. When keys have tags applied, it fails due to the lack of permission

### CODE REVIEW

**Comment by 0verc1ocker** [comment]
Also need `kms:UntagResource` for when the KMS key is rotated through this module or renamed.

**Comment by Gowiem** [comment]
@erikdj can you rebase off master -- I believe that will fix your tests and then we can get this merged. Also if you can add the Untag* permissions then that would be appreciated as well.

**Comment by Gowiem** [comment]
Closed #6

**Comment by erikdj** [comment]
Rebased and added kms:Untag* permissions per request from @0verc1ocker

**Review by aknysh — APPROVED** [review]
thanks @erikdj

**Pull request merged**
