### PR TITLE
Add kms actions

### LINKED ISSUE #30: KMS policy does not allow key to be used with s3
## Describe the Bug
The policy attached to generated key does not allow the key to be used to access s3 objects encrypted with said key.  When trying to access an s3 object, an access denied error is generated.

## Expected Behavior
The key policy should include at minimum
```
"kms:Decrypt*",
"kms:GenerateDataKey*"
```
Adding these actions fixes the issue.

### PR DESCRIPTION
**Pull request by bwmetcalf**
## what
* Add permissions to allow key to be used

## why
* The current policy does not allow key to be used to access encrypted objects.  Added
```
kms:Decrypt
kms:GenerateDataKey
```
as most if not all other actions are already allowed.

## references
* Closes #30

### CODE REVIEW

**Comment by bwmetcalf** [comment]
@aknysh @Nuru Could you guys take a look and approve/merge?  Thanks.

**Comment by vsimon** [comment]
Friendly ping for reviewing this? 🙏

**Comment by jamengual** [comment]
for vpc flow logs to work the decryption is not needed so there is no need to add it.
If you need another user or process to decrypt then you can manage the policy elsewhere.
We try to minimize the permission for each module base on its purpose of it and try to maintain the rule of least privilege.

**Comment by bwmetcalf** [comment]
> for vpc flow logs to work the decryption is not needed so there is no need to add it.
> If you need another user or process to decrypt then you can manage the policy elsewhere.
> We try to minimize the permission for each module base on its purpose of it and try to maintain the rule of least privilege.

I don't believe this will work as the policy does not explicitly allow IAM policies to control access to the CMK.  See https://docs.aws.amazon.com/kms/latest/developerguide/key-policies.html#key-policy-default-allow-root-enable-iam.

**Comment by nitrocode** [comment]
This repo would be a good candidate to use this module https://github.com/cloudposse/terraform-aws-iam-policy or using the terraform code as is and just exposing the statements as a variable

1. Create a new input variable here called something like `iam_policy_statements` or `<service>_iam_policy_statements` which is equivalent
1. Pass in existing statements

This way the consumer of the module can overwrite the permissions.

**Comment by jamengual** [comment]
IF you are using the same policy attached to another role and trying to decrypt then it will not work.
but again the purpose of the module is to send vpc-flow logs to s3 so the question is, is `decrypt` necessary?
KMS should be harder as the keys to the kingdom so the least privilege is better.

**Comment by bwmetcalf** [comment]
> IF you are using the same policy attached to another role and trying to decrypt then it will not work.
> but again the purpose of the module is to send vpc-flow logs to s3 so the question is, is `decrypt` necessary?
> KMS should be guarded as the keys to the kingdom so the least privilege is better.

For testing, I added the following policy to my iam role:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "kms:*"
            ],
            "Resource": "*"
        }
    ]
}
```
but I still cannot access the s3 objects.  However, if I add `Decrypt` and `GenerateDataKey` to the kms policy, it works even without the above policy added to my role.  It seems the key policy needs to specify what actions are allowed to be governed by iam policies.

**Comment by jamengual** [comment]
KMS key needs to be allowed from the Principal side (user/role) and from the KMS policy side explicitly.
The reason why that policy you posted works is because the account you are using is in the same `root` account but is NOT recommended at all.

from the same link you posted:

```{
  "Sid": "Allow use of the key",
  "Effect": "Allow",
  "Principal": {"AWS": [
    "arn:aws:iam::111122223333:user/CMKUser",
    "arn:aws:iam::111122223333:role/CMKRole",
  ]},
  "Action": [
    "kms:Encrypt",
    "kms:Decrypt",
    "kms:ReEncrypt*",
    "kms:GenerateDataKey*",
    "kms:DescribeKey"
  ],
  "Resource": "*"
}```

in this case you change the kms key policy in using another module/process to allow this users/role to decrypt.

do you get the idea?

**Comment by woz5999** [comment]
@jamengual Accoridng to the KMS key policy docs, `Every customer master key (CMK) must have exactly one key policy.` If this module is creating and managing the key policy for this key, it's not possible to change/manage that policy from another module. 

As it is right now, this module is ONLY effective for sending flow logs to s3. It is not possible to read the flow logs written by this module.  Unless I'm missing something, the current implementation seems a bit pointless without the ability to actually consume the flow logs after writing.

**Comment by jamengual** [comment]
@woz5999 I see, now I understand why the policy needs to be changed here instead, in that case, @nitrocode suggestion of adding a way to pass the policy is a better option using a aws_iam_policy_document that we merge from an input variable

**Comment by bwmetcalf** [comment]
> @woz5999 I see, now I understand why the policy needs to be changed here instead, in that case, @nitrocode suggestion of adding a way to pass the policy is a better option using a aws_iam_policy_document that we merge from an input variable

I'll update my PR to use this method.

**Comment by bwmetcalf** [comment]
This PR can be closed.  Reference https://github.com/cloudposse/terraform-aws-vpc-flow-logs-s3-bucket/pull/33 for correct fix.

**Pull request closed without merging**
